// Mock data for the Al Karma Developments Admin Dashboard

export const dashboardStats = [
  {
    id: 1,
    title: "Total Active Residents",
    value: "1,248",
    change: "+12.5%",
    trend: "up" as const,
    icon: "users",
  },
  {
    id: 2,
    title: "Units Occupied",
    value: "847/1,200",
    change: "70.6%",
    trend: "neutral" as const,
    icon: "building",
  },
  {
    id: 3,
    title: "QR Codes Generated Today",
    value: "156",
    change: "+8.2%",
    trend: "up" as const,
    icon: "qrcode",
  },
  {
    id: 4,
    title: "Pending Service Requests",
    value: "23",
    change: "-15.3%",
    trend: "down" as const,
    icon: "clipboard",
  },
  {
    id: 5,
    title: "Outstanding Payments",
    value: "EGP 125,450",
    change: "-5.2%",
    trend: "down" as const,
    icon: "wallet",
  },
  {
    id: 6,
    title: "Active Security Alerts",
    value: "2",
    change: "0%",
    trend: "neutral" as const,
    icon: "shield",
  },
];

export const visitorTrafficData = [
  { date: "Jan 1", visitors: 45 },
  { date: "Jan 3", visitors: 52 },
  { date: "Jan 5", visitors: 48 },
  { date: "Jan 7", visitors: 61 },
  { date: "Jan 9", visitors: 55 },
  { date: "Jan 11", visitors: 67 },
  { date: "Jan 13", visitors: 58 },
  { date: "Jan 15", visitors: 72 },
  { date: "Jan 17", visitors: 65 },
  { date: "Jan 19", visitors: 78 },
  { date: "Jan 21", visitors: 70 },
  { date: "Jan 23", visitors: 82 },
  { date: "Jan 25", visitors: 75 },
  { date: "Jan 27", visitors: 88 },
  { date: "Jan 29", visitors: 80 },
];

export const serviceRequestsData = [
  { name: "Maintenance", value: 145, fill: "#0B5FFF" },
  { name: "Cleaning", value: 89, fill: "#00B386" },
  { name: "Amenities", value: 67, fill: "#3B82F6" },
  { name: "Security", value: 34, fill: "#F59E0B" },
  { name: "Other", value: 28, fill: "#64748B" },
];

export const monthlyRevenueData = [
  { month: "Aug", revenue: 185000 },
  { month: "Sep", revenue: 192000 },
  { month: "Oct", revenue: 178000 },
  { month: "Nov", revenue: 205000 },
  { month: "Dec", revenue: 198000 },
  { month: "Jan", revenue: 215000 },
];

export const recentActivities = [
  {
    id: 1,
    user: "Ahmed Hassan",
    action: "submitted a maintenance request",
    target: "Unit A-205",
    timestamp: "2 minutes ago",
    type: "maintenance",
  },
  {
    id: 2,
    user: "Sara Mohamed",
    action: "generated a visitor pass",
    target: "Guest: John Smith",
    timestamp: "15 minutes ago",
    type: "access",
  },
  {
    id: 3,
    user: "Admin",
    action: "approved payment for",
    target: "Unit B-102 - EGP 2,500",
    timestamp: "1 hour ago",
    type: "payment",
  },
  {
    id: 4,
    user: "Mohamed Ali",
    action: "booked club house",
    target: "March 15, 2025",
    timestamp: "2 hours ago",
    type: "booking",
  },
  {
    id: 5,
    user: "Security Desk",
    action: "reported security incident",
    target: "Block C Entrance",
    timestamp: "3 hours ago",
    type: "security",
  },
  {
    id: 6,
    user: "Fatma Ibrahim",
    action: "registered for gym access",
    target: "Premium Membership",
    timestamp: "4 hours ago",
    type: "amenity",
  },
];

export const residents = [
  {
    id: 1,
    name: "Ahmed Hassan Mohamed",
    nameAr: "أحمد حسن محمد",
    nationalId: "****5678",
    mobile: "+20 101 234 5678",
    email: "ahmed.hassan@email.com",
    units: ["A-205", "A-206"],
    status: "Active",
    registrationDate: "15/01/2024",
    avatar: "AH",
  },
  {
    id: 2,
    name: "Sara Mohamed Ali",
    nameAr: "سارة محمد علي",
    nationalId: "****9012",
    mobile: "+20 122 345 6789",
    email: "sara.mohamed@email.com",
    units: ["B-102"],
    status: "Active",
    registrationDate: "20/02/2024",
    avatar: "SM",
  },
  {
    id: 3,
    name: "Mohamed Ali Ibrahim",
    nameAr: "محمد علي إبراهيم",
    nationalId: "****3456",
    mobile: "+20 100 456 7890",
    email: "mohamed.ali@email.com",
    units: ["C-301"],
    status: "Active",
    registrationDate: "10/03/2024",
    avatar: "MA",
  },
  {
    id: 4,
    name: "Fatma Ibrahim Hassan",
    nameAr: "فاطمة إبراهيم حسن",
    nationalId: "****7890",
    mobile: "+20 111 567 8901",
    email: "fatma.ibrahim@email.com",
    units: ["D-405"],
    status: "Pending",
    registrationDate: "05/04/2024",
    avatar: "FI",
  },
  {
    id: 5,
    name: "Omar Khaled Ahmed",
    nameAr: "عمر خالد أحمد",
    nationalId: "****2345",
    mobile: "+20 120 678 9012",
    email: "omar.khaled@email.com",
    units: ["E-501", "E-502"],
    status: "Active",
    registrationDate: "25/05/2024",
    avatar: "OK",
  },
];

export const units = [
  {
    id: 1,
    project: "Al Karma Residence",
    building: "Block A",
    unitNumber: "A-205",
    type: "Apartment",
    size: "145 m²",
    status: "Occupied",
    owner: "Ahmed Hassan Mohamed",
    tenant: null,
    lastUpdated: "15/01/2024",
  },
  {
    id: 2,
    project: "Al Karma Residence",
    building: "Block B",
    unitNumber: "B-102",
    type: "Villa",
    size: "320 m²",
    status: "Occupied",
    owner: "Sara Mohamed Ali",
    tenant: "Omar Khaled Ahmed",
    lastUpdated: "20/02/2024",
  },
  {
    id: 3,
    project: "Al Karma Gardens",
    building: "Block C",
    unitNumber: "C-301",
    type: "Townhouse",
    size: "210 m²",
    status: "Under Maintenance",
    owner: "Mohamed Ali Ibrahim",
    tenant: null,
    lastUpdated: "10/03/2024",
  },
  {
    id: 4,
    project: "Al Karma Towers",
    building: "Block D",
    unitNumber: "D-405",
    type: "Apartment",
    size: "165 m²",
    status: "Available",
    owner: null,
    tenant: null,
    lastUpdated: "05/04/2024",
  },
  {
    id: 5,
    project: "Al Karma Residence",
    building: "Block E",
    unitNumber: "E-501",
    type: "Penthouse",
    size: "450 m²",
    status: "Occupied",
    owner: "Fatma Ibrahim Hassan",
    tenant: null,
    lastUpdated: "25/05/2024",
  },
];

export const serviceRequests = [
  {
    id: "SR-2025-001",
    resident: "Ahmed Hassan",
    unit: "A-205",
    type: "Plumbing",
    category: "Maintenance",
    description: "Leaking faucet in master bathroom",
    priority: "Medium",
    status: "In Progress",
    assignedTo: "Mohamed Maintenance Team",
    createdDate: "12/01/2025",
    updatedDate: "12/01/2025",
  },
  {
    id: "SR-2025-002",
    resident: "Sara Mohamed",
    unit: "B-102",
    type: "Electrical",
    category: "Maintenance",
    description: "Power outlet not working in living room",
    priority: "High",
    status: "Pending",
    assignedTo: null,
    createdDate: "12/01/2025",
    updatedDate: "12/01/2025",
  },
  {
    id: "SR-2025-003",
    resident: "Mohamed Ali",
    unit: "C-301",
    type: "Cleaning",
    category: "Cleaning",
    description: "Weekly cleaning service",
    priority: "Low",
    status: "Completed",
    assignedTo: "Cleaning Services",
    createdDate: "10/01/2025",
    updatedDate: "11/01/2025",
  },
];

export const accessLogs = [
  {
    id: "QR-2025-0156",
    type: "Visitor Pass",
    generatedBy: "Ahmed Hassan",
    forName: "John Smith",
    company: null,
    validFrom: "12/01/2025 10:00 AM",
    validTo: "12/01/2025 08:00 PM",
    gate: "Main Gate",
    scanHistory: 1,
    status: "Active",
  },
  {
    id: "QR-2025-0155",
    type: "Delivery Access",
    generatedBy: "Sara Mohamed",
    forName: "Amazon Courier",
    company: "Amazon",
    validFrom: "12/01/2025 02:00 PM",
    validTo: "12/01/2025 04:00 PM",
    gate: "Service Gate",
    scanHistory: 0,
    status: "Active",
  },
  {
    id: "QR-2025-0154",
    type: "Contractor Pass",
    generatedBy: "Admin",
    forName: "Ahmed Electrician",
    company: "Fix-It Services",
    validFrom: "11/01/2025 08:00 AM",
    validTo: "11/01/2025 06:00 PM",
    gate: "Main Gate",
    scanHistory: 2,
    status: "Expired",
  },
];

export const leases = [
  {
    id: "LS-2024-001",
    unit: "B-102",
    owner: "Sara Mohamed Ali",
    tenant: "Omar Khaled Ahmed",
    startDate: "01/06/2024",
    endDate: "31/05/2025",
    monthlyRent: "EGP 8,500",
    deposit: "EGP 17,000",
    status: "Active",
    paymentStatus: "On Time",
  },
  {
    id: "LS-2024-002",
    unit: "C-405",
    owner: "Mohamed Ali Ibrahim",
    tenant: "Hassan Ahmed Ali",
    startDate: "15/03/2024",
    endDate: "14/03/2025",
    monthlyRent: "EGP 6,200",
    deposit: "EGP 12,400",
    status: "Active",
    paymentStatus: "Overdue",
  },
  {
    id: "LS-2023-015",
    unit: "A-301",
    owner: "Fatma Ibrahim Hassan",
    tenant: "Nour Mahmoud",
    startDate: "01/01/2024",
    endDate: "31/12/2024",
    monthlyRent: "EGP 7,800",
    deposit: "EGP 15,600",
    status: "Expired",
    paymentStatus: "Completed",
  },
];

export const complaints = [
  {
    id: "CMP-2025-045",
    reporter: "Ahmed Hassan",
    unit: "A-205",
    category: "Noise Complaint",
    description: "Loud music from neighboring unit after 11 PM",
    priority: "Medium",
    status: "In Progress",
    assignedTo: "Security Team",
    createdDate: "10/01/2025",
    evidence: true,
  },
  {
    id: "CMP-2025-046",
    reporter: "Sara Mohamed",
    unit: "B-102",
    category: "Parking Violation",
    description: "Unauthorized vehicle in reserved parking spot",
    priority: "High",
    status: "Resolved",
    assignedTo: "Security Team",
    createdDate: "11/01/2025",
    evidence: true,
  },
  {
    id: "CMP-2025-047",
    reporter: "Mohamed Ali",
    unit: "C-301",
    category: "Common Area",
    description: "Broken light in hallway on 3rd floor",
    priority: "Low",
    status: "New",
    assignedTo: null,
    createdDate: "12/01/2025",
    evidence: false,
  },
];

export const violations = [
  {
    id: "VIO-2025-012",
    offender: "Unit D-210",
    type: "Parking Violation",
    description: "Parking in fire lane",
    fineAmount: "EGP 500",
    status: "Pending Payment",
    appealStatus: "None",
    date: "09/01/2025",
  },
  {
    id: "VIO-2025-013",
    offender: "Unit E-105",
    type: "Noise Violation",
    description: "Excessive noise after quiet hours",
    fineAmount: "EGP 300",
    status: "Paid",
    appealStatus: "None",
    date: "10/01/2025",
  },
];

export const invoices = [
  {
    id: "INV-2025-0234",
    unit: "A-205",
    resident: "Ahmed Hassan",
    type: "Maintenance Fee",
    amount: "EGP 2,500",
    dueDate: "15/01/2025",
    status: "Paid",
    paidDate: "12/01/2025",
  },
  {
    id: "INV-2025-0235",
    unit: "B-102",
    resident: "Sara Mohamed",
    type: "Monthly Rent",
    amount: "EGP 8,500",
    dueDate: "01/02/2025",
    status: "Pending",
    paidDate: null,
  },
  {
    id: "INV-2025-0236",
    unit: "C-301",
    resident: "Mohamed Ali",
    type: "Club Membership",
    amount: "EGP 1,200",
    dueDate: "10/01/2025",
    status: "Overdue",
    paidDate: null,
  },
];

export const banners = [
  {
    id: 1,
    title: "Summer Festival 2025",
    titleAr: "مهرجان الصيف 2025",
    status: "Active",
    startDate: "01/06/2025",
    endDate: "30/06/2025",
    views: 1248,
    clicks: 89,
    targetAudience: "All Residents",
  },
  {
    id: 2,
    title: "New Gym Equipment",
    titleAr: "معدات جديدة للنادي الرياضي",
    status: "Scheduled",
    startDate: "15/01/2025",
    endDate: "28/02/2025",
    views: 0,
    clicks: 0,
    targetAudience: "Al Karma Residence",
  },
  {
    id: 3,
    title: "Payment Reminder",
    titleAr: "تذكير بالدفع",
    status: "Expired",
    startDate: "01/12/2024",
    endDate: "31/12/2024",
    views: 2341,
    clicks: 156,
    targetAudience: "All Residents",
  },
];

export const notifications = [
  {
    id: 1,
    title: "Maintenance Scheduled",
    message: "Water supply will be interrupted on Jan 15 from 9 AM to 2 PM",
    type: "Announcement",
    channels: ["Push", "SMS", "Email"],
    targetAudience: "Block A & B",
    status: "Sent",
    sentDate: "08/01/2025",
    delivered: 245,
    read: 198,
  },
  {
    id: 2,
    title: "Monthly Payment Reminder",
    message: "Your maintenance fee is due on January 15, 2025",
    type: "Payment",
    channels: ["Push", "SMS"],
    targetAudience: "All Residents",
    status: "Scheduled",
    sentDate: "13/01/2025",
    delivered: 0,
    read: 0,
  },
];

export const securityIncidents = [
  {
    id: "SEC-2025-008",
    type: "Emergency Alert",
    location: "Block C - Unit 305",
    resident: "Fatma Ibrahim",
    description: "Medical emergency reported",
    priority: "Critical",
    status: "Resolved",
    responseTime: "4 minutes",
    reportedAt: "11/01/2025 03:45 PM",
    resolvedAt: "11/01/2025 04:20 PM",
  },
  {
    id: "SEC-2025-009",
    type: "Suspicious Activity",
    location: "Main Gate",
    resident: null,
    description: "Unidentified person attempting entry",
    priority: "High",
    status: "In Progress",
    responseTime: "2 minutes",
    reportedAt: "12/01/2025 10:30 PM",
    resolvedAt: null,
  },
];

export const amenities = [
  {
    id: 1,
    name: "Swimming Pool",
    type: "Recreation",
    capacity: 50,
    operatingHours: "06:00 AM - 10:00 PM",
    status: "Available",
    bookingsToday: 12,
    maintenanceSchedule: "Every Monday 6-8 AM",
  },
  {
    id: 2,
    name: "Gym & Fitness Center",
    type: "Fitness",
    capacity: 30,
    operatingHours: "05:00 AM - 11:00 PM",
    status: "Available",
    bookingsToday: 28,
    maintenanceSchedule: "Every Sunday 5-7 AM",
  },
  {
    id: 3,
    name: "Club House",
    type: "Events",
    capacity: 100,
    operatingHours: "08:00 AM - 12:00 AM",
    status: "Booked",
    bookingsToday: 1,
    maintenanceSchedule: "As needed",
  },
  {
    id: 4,
    name: "Children's Playground",
    type: "Recreation",
    capacity: 40,
    operatingHours: "06:00 AM - 08:00 PM",
    status: "Under Maintenance",
    bookingsToday: 0,
    maintenanceSchedule: "12/01/2025 - 15/01/2025",
  },
];

export const amenityBookings = [
  {
    id: "BK-2025-089",
    resident: "Ahmed Hassan",
    amenity: "Club House",
    date: "15/01/2025",
    timeSlot: "06:00 PM - 10:00 PM",
    purpose: "Birthday Party",
    status: "Confirmed",
    guests: 45,
  },
  {
    id: "BK-2025-090",
    resident: "Sara Mohamed",
    amenity: "Swimming Pool",
    date: "13/01/2025",
    timeSlot: "10:00 AM - 12:00 PM",
    purpose: "Private Session",
    status: "Pending",
    guests: 8,
  },
];

export const smartDevices = [
  {
    id: 1,
    unit: "A-205",
    deviceType: "Smart Thermostat",
    deviceName: "Living Room AC",
    status: "Online",
    lastActive: "2 minutes ago",
    integration: "Connected",
  },
  {
    id: 2,
    unit: "A-205",
    deviceType: "Smart Lock",
    deviceName: "Main Door",
    status: "Online",
    lastActive: "5 minutes ago",
    integration: "Connected",
  },
  {
    id: 3,
    unit: "B-102",
    deviceType: "Smart Lighting",
    deviceName: "Bedroom Lights",
    status: "Offline",
    lastActive: "2 hours ago",
    integration: "Error",
  },
];
